server:
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: file:/etc/siga/siga.localhost.keystore.p12
    key-store-password: changeit

spring:
  profiles:
    active: digidoc4jTest,datafileContainer,smartId,mobileId
  sql:
    init:
      platform: postgresql
      continue-on-error: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master-dev.yaml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://siga-db:5432/siga_db
    username: sa
    password: ""
  data:
    redis:
      cluster:
        nodes: siga-redis-1:6379,siga-redis-2:6380,siga-redis-3:6381
      lettuce:
        cluster:
          refresh:
            period: 30s
            adaptive: true
            dynamic-refresh-sources: true

logging:
  config: file:/etc/siga/logback.xml

siga:
  session-storage:
    ignite:
      configuration-location: file:/etc/siga/ignite-configuration.xml
    application-cache-version: v1
  dd4j:
    configuration-location: digidoc4j-test.yaml
    tsl-refresh-job-cron: "0 0 3 * * *"
  siva:
    url: https://siva-demo.eesti.ee/V3
    trust-store: file:/etc/siga/siva.truststore.p12
    trust-store-password: changeit
    connection-timeout: PT20S
    write-timeout: PT20S
    read-timeout: PT20S
    max-in-memory-size: 10MB
  midrest:
    allowed-countries: EE, LT
    url: https://tsp.demo.sk.ee/mid-api
    status-polling-delay: 0
    truststore-path: file:/etc/siga/mid.truststore.p12
    truststore-password: changeit
  security:
    jasypt:
      encryption-algo: PBEWITHSHA-256AND256BITAES-CBC-BC
      encryption-key: encryptorKey
    hmac:
      expiration: 60
      clock-skew: 10
  sid:
    allowedCountries: EE, LT, LV
    url: https://sid.demo.sk.ee/smart-id-rp/v2/
    interaction-type: DISPLAY_TEXT_AND_PIN
    session-status-response-socket-open-time: 1000
    status-polling-delay: 0
    truststore-path: file:/etc/siga/sid.truststore.p12
    truststore-password: changeit
