//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.13 at 05:34:52 PM EET 
//


package com.nortal.sample.mobileid.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.sk.ee/DigiDocService/DigiDocService_2_3.wsdl}AbstractGetStatusResponseType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Sesscode" type="{http://www.sk.ee/DigiDocService/DigiDocService_2_3.wsdl}SessionIdType"/&gt;
 *         &lt;element name="CertificateData" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *         &lt;element name="RevocationData" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sesscode",
    "certificateData",
    "revocationData"
})
@XmlRootElement(name = "GetMobileSignHashStatusResponse")
public class GetMobileSignHashStatusResponse
    extends AbstractGetStatusResponseType
{

    @XmlElement(name = "Sesscode", required = true)
    protected String sesscode;
    @XmlElement(name = "CertificateData")
    protected byte[] certificateData;
    @XmlElement(name = "RevocationData")
    protected byte[] revocationData;

    /**
     * Gets the value of the sesscode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSesscode() {
        return sesscode;
    }

    /**
     * Sets the value of the sesscode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSesscode(String value) {
        this.sesscode = value;
    }

    /**
     * Gets the value of the certificateData property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getCertificateData() {
        return certificateData;
    }

    /**
     * Sets the value of the certificateData property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setCertificateData(byte[] value) {
        this.certificateData = value;
    }

    /**
     * Gets the value of the revocationData property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getRevocationData() {
        return revocationData;
    }

    /**
     * Sets the value of the revocationData property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setRevocationData(byte[] value) {
        this.revocationData = value;
    }

}
