//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.13 at 05:34:52 PM EET 
//


package com.nortal.sample.mobileid.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.sk.ee/DigiDocService/DigiDocService_2_3.wsdl}AbstractRequestType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SPChallenge" type="{http://www.sk.ee/DigiDocService/DigiDocService_2_3.wsdl}HexString20" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "spChallenge"
})
@XmlRootElement(name = "MobileAuthenticateRequest")
public class MobileAuthenticateRequest
    extends AbstractRequestType
{

    @XmlElement(name = "SPChallenge")
    protected String spChallenge;

    /**
     * Gets the value of the spChallenge property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSPChallenge() {
        return spChallenge;
    }

    /**
     * Sets the value of the spChallenge property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSPChallenge(String value) {
        this.spChallenge = value;
    }

}
