//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.13 at 05:34:52 PM EET 
//


package com.nortal.sample.mobileid.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.sk.ee/DigiDocService/DigiDocService_2_3.wsdl}AbstractRequestType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Hash" type="{http://www.sk.ee/DigiDocService/DigiDocService_2_3.wsdl}HexString128"/&gt;
 *         &lt;element name="HashType" type="{http://www.sk.ee/DigiDocService/DigiDocService_2_3.wsdl}HashType"/&gt;
 *         &lt;element name="KeyID" type="{http://www.sk.ee/DigiDocService/DigiDocService_2_3.wsdl}KeyID" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "hash",
    "hashType",
    "keyID"
})
@XmlRootElement(name = "MobileSignHashRequest")
public class MobileSignHashRequest
    extends AbstractRequestType
{

    @XmlElement(name = "Hash", required = true)
    protected String hash;
    @XmlElement(name = "HashType", required = true)
    @XmlSchemaType(name = "string")
    protected HashType hashType;
    @XmlElement(name = "KeyID")
    @XmlSchemaType(name = "string")
    protected KeyID keyID;

    /**
     * Gets the value of the hash property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHash() {
        return hash;
    }

    /**
     * Sets the value of the hash property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHash(String value) {
        this.hash = value;
    }

    /**
     * Gets the value of the hashType property.
     * 
     * @return
     *     possible object is
     *     {@link HashType }
     *     
     */
    public HashType getHashType() {
        return hashType;
    }

    /**
     * Sets the value of the hashType property.
     * 
     * @param value
     *     allowed object is
     *     {@link HashType }
     *     
     */
    public void setHashType(HashType value) {
        this.hashType = value;
    }

    /**
     * Gets the value of the keyID property.
     * 
     * @return
     *     possible object is
     *     {@link KeyID }
     *     
     */
    public KeyID getKeyID() {
        return keyID;
    }

    /**
     * Sets the value of the keyID property.
     * 
     * @param value
     *     allowed object is
     *     {@link KeyID }
     *     
     */
    public void setKeyID(KeyID value) {
        this.keyID = value;
    }

}
