//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.13 at 05:34:52 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.sk.ee/DigiDocService/DigiDocService_2_3.wsdl")
package com.nortal.sample.mobileid.model;
