//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.13 at 05:34:52 PM EET 
//


package ee.openeid.siga.mobileid.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="IDCode" type="{http://www.sk.ee/DigiDocService/DigiDocService_2_3.wsdl}IdCodeType"/&gt;
 *         &lt;element name="Country" type="{http://www.sk.ee/DigiDocService/DigiDocService_2_3.wsdl}CountryType"/&gt;
 *         &lt;element name="ReturnCertData" type="{http://www.sk.ee/DigiDocService/DigiDocService_2_3.wsdl}ReturnCertDataType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "idCode",
    "country",
    "returnCertData"
})
@XmlRootElement(name = "GetMobileCertByIDCodeRequest")
public class GetMobileCertByIDCodeRequest {

    @XmlElement(name = "IDCode", required = true)
    protected String idCode;
    @XmlElement(name = "Country", required = true)
    protected String country;
    @XmlElement(name = "ReturnCertData", required = true)
    @XmlSchemaType(name = "string")
    protected ReturnCertDataType returnCertData;

    /**
     * Gets the value of the idCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDCode() {
        return idCode;
    }

    /**
     * Sets the value of the idCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDCode(String value) {
        this.idCode = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the returnCertData property.
     * 
     * @return
     *     possible object is
     *     {@link ReturnCertDataType }
     *     
     */
    public ReturnCertDataType getReturnCertData() {
        return returnCertData;
    }

    /**
     * Sets the value of the returnCertData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReturnCertDataType }
     *     
     */
    public void setReturnCertData(ReturnCertDataType value) {
        this.returnCertData = value;
    }

}
