//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.13 at 05:34:52 PM EET 
//


package ee.openeid.siga.mobileid.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AuthCertStatus" type="{http://www.sk.ee/DigiDocService/DigiDocService_2_3.wsdl}String2To7" minOccurs="0"/&gt;
 *         &lt;element name="SignCertStatus" type="{http://www.sk.ee/DigiDocService/DigiDocService_2_3.wsdl}String2To7" minOccurs="0"/&gt;
 *         &lt;element name="AuthCertData" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *         &lt;element name="SignCertData" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "authCertStatus",
    "signCertStatus",
    "authCertData",
    "signCertData"
})
@XmlRootElement(name = "GetMobileCertByIDCodeResponse")
public class GetMobileCertByIDCodeResponse {

    @XmlElement(name = "AuthCertStatus")
    protected String authCertStatus;
    @XmlElement(name = "SignCertStatus")
    protected String signCertStatus;
    @XmlElement(name = "AuthCertData")
    protected byte[] authCertData;
    @XmlElement(name = "SignCertData")
    protected byte[] signCertData;

    /**
     * Gets the value of the authCertStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthCertStatus() {
        return authCertStatus;
    }

    /**
     * Sets the value of the authCertStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthCertStatus(String value) {
        this.authCertStatus = value;
    }

    /**
     * Gets the value of the signCertStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignCertStatus() {
        return signCertStatus;
    }

    /**
     * Sets the value of the signCertStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignCertStatus(String value) {
        this.signCertStatus = value;
    }

    /**
     * Gets the value of the authCertData property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getAuthCertData() {
        return authCertData;
    }

    /**
     * Sets the value of the authCertData property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setAuthCertData(byte[] value) {
        this.authCertData = value;
    }

    /**
     * Gets the value of the signCertData property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getSignCertData() {
        return signCertData;
    }

    /**
     * Sets the value of the signCertData property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setSignCertData(byte[] value) {
        this.signCertData = value;
    }

}
