package ee.openeid.siga.common.exception;

public enum ErrorResponseCode {
    AUTHORIZATION_ERROR,
    CLIENT_EXCEPTION,
    CONNECTION_LIMIT_EXCEPTION,
    DUPLICATE_DATA_FILE_EXCEPTION,
    INTERNAL_SERVER_ERROR,
    INVALID_CERTIFICATE_EXCEPTION,
    INVALID_CONTAINER_EXCEPTION,
    INVALID_HASH_ALGORITHM_EXCEPTION,
    INVALID_LANGUAGE_EXCEPTION,
    INVALID_SESSION_DATA_EXCEPTION,
    INVALID_SIGNATURE_EXCEPTION,
    MID_EXCEPTION,
    REQUEST_SIZE_LIMIT_EXCEPTION,
    REQUEST_VALIDATION_EXCEPTION,
    RESOURCE_NOT_FOUND_EXCEPTION,
    SIGNATURE_CREATION_EXCEPTION,
    SIGNATURE_EXISTS_EXCEPTION,
    SMARTID_EXCEPTION
}
