//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.26 at 05:42:17 PM EET 
//


package ee.openeid.siga.mobileid.model.dds;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AuthCertStatus" type="{http://www.sk.ee/DigiDocService/DigiDocService_2_3.wsdl}String2To7" minOccurs="0"/&gt;
 *         &lt;element name="SignCertStatus" type="{http://www.sk.ee/DigiDocService/DigiDocService_2_3.wsdl}String2To7" minOccurs="0"/&gt;
 *         &lt;element name="AuthCertData" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SignCertData" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "authCertStatus",
        "signCertStatus",
        "authCertData",
        "signCertData"
})
@XmlRootElement(name = "GetMobileCertificateResponse")
public class GetMobileCertificateResponse {

    @XmlElement(name = "AuthCertStatus")
    protected String authCertStatus;
    @XmlElement(name = "SignCertStatus")
    protected String signCertStatus;
    @XmlElement(name = "AuthCertData")
    protected String authCertData;
    @XmlElement(name = "SignCertData")
    protected String signCertData;

    /**
     * Gets the value of the authCertStatus property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAuthCertStatus() {
        return authCertStatus;
    }

    /**
     * Sets the value of the authCertStatus property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAuthCertStatus(String value) {
        this.authCertStatus = value;
    }

    /**
     * Gets the value of the signCertStatus property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSignCertStatus() {
        return signCertStatus;
    }

    /**
     * Sets the value of the signCertStatus property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSignCertStatus(String value) {
        this.signCertStatus = value;
    }

    /**
     * Gets the value of the authCertData property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAuthCertData() {
        return authCertData;
    }

    /**
     * Sets the value of the authCertData property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAuthCertData(String value) {
        this.authCertData = value;
    }

    /**
     * Gets the value of the signCertData property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSignCertData() {
        return signCertData;
    }

    /**
     * Sets the value of the signCertData property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSignCertData(String value) {
        this.signCertData = value;
    }

}
