//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.26 at 05:42:17 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.sk.ee/DigiDocService/DigiDocService_2_3.wsdl")
package ee.openeid.siga.mobileid.model.dds;
