//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.26 at 05:42:17 PM EET 
//


package ee.openeid.siga.mobileid.model.dds;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReturnCertDataType.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ReturnCertDataType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="AUTH"/&gt;
 *     &lt;enumeration value="SIGN"/&gt;
 *     &lt;enumeration value="BOTH"/&gt;
 *     &lt;enumeration value="AUTHRSA"/&gt;
 *     &lt;enumeration value="AUTHECC"/&gt;
 *     &lt;enumeration value="SIGNRSA"/&gt;
 *     &lt;enumeration value="SIGNECC"/&gt;
 *     &lt;enumeration value="BOTHRSA"/&gt;
 *     &lt;enumeration value="BOTHECC"/&gt;
 *     &lt;enumeration value="NONE"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 */
@XmlType(name = "ReturnCertDataType")
@XmlEnum
public enum ReturnCertDataType {

    AUTH,
    SIGN,
    BOTH,
    AUTHRSA,
    AUTHECC,
    SIGNRSA,
    SIGNECC,
    BOTHRSA,
    BOTHECC,
    NONE;

    public static ReturnCertDataType fromValue(String v) {
        return valueOf(v);
    }

    public String value() {
        return name();
    }

}
