//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.26 at 05:42:17 PM EET 
//


package ee.openeid.siga.mobileid.model.mid;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for AbstractResponseType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="AbstractResponseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.sk.ee/DigiDocService/DigiDocService_2_3.wsdl}SessionAwareType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ChallengeID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractResponseType", propOrder = {
        "challengeID"
})
@XmlSeeAlso({
        MobileAuthenticateResponse.class,
        MobileSignHashResponse.class
})
public abstract class AbstractResponseType
        extends SessionAwareType {

    @XmlElement(name = "ChallengeID", required = true)
    protected String challengeID;

    /**
     * Gets the value of the challengeID property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getChallengeID() {
        return challengeID;
    }

    /**
     * Sets the value of the challengeID property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setChallengeID(String value) {
        this.challengeID = value;
    }

}
