//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.26 at 05:42:17 PM EET 
//


package ee.openeid.siga.mobileid.model.mid;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.sk.ee/DigiDocService/DigiDocService_2_3.wsdl}AbstractGetStatusRequestType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ReturnCertData" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="ReturnRevocationData" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "returnCertData",
        "returnRevocationData"
})
@XmlRootElement(name = "GetMobileAuthenticateStatusRequest")
public class GetMobileAuthenticateStatusRequest
        extends AbstractGetStatusRequestType {

    @XmlElement(name = "ReturnCertData")
    protected Boolean returnCertData;
    @XmlElement(name = "ReturnRevocationData")
    protected Boolean returnRevocationData;

    /**
     * Gets the value of the returnCertData property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public Boolean isReturnCertData() {
        return returnCertData;
    }

    /**
     * Sets the value of the returnCertData property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setReturnCertData(Boolean value) {
        this.returnCertData = value;
    }

    /**
     * Gets the value of the returnRevocationData property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public Boolean isReturnRevocationData() {
        return returnRevocationData;
    }

    /**
     * Sets the value of the returnRevocationData property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setReturnRevocationData(Boolean value) {
        this.returnRevocationData = value;
    }

}
