//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.26 at 05:42:17 PM EET 
//


package ee.openeid.siga.mobileid.model.mid;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the ee.openeid.siga.mobileid.model.mid package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ee.openeid.siga.mobileid.model.mid
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetMobileCertByIDCodeRequest }
     */
    public GetMobileCertByIDCodeRequest createGetMobileCertByIDCodeRequest() {
        return new GetMobileCertByIDCodeRequest();
    }

    /**
     * Create an instance of {@link GetMobileCertByIDCodeResponse }
     */
    public GetMobileCertByIDCodeResponse createGetMobileCertByIDCodeResponse() {
        return new GetMobileCertByIDCodeResponse();
    }

    /**
     * Create an instance of {@link MobileSignHashByIDCodeRequest }
     */
    public MobileSignHashByIDCodeRequest createMobileSignHashByIDCodeRequest() {
        return new MobileSignHashByIDCodeRequest();
    }

    /**
     * Create an instance of {@link MobileSignHashRequest }
     */
    public MobileSignHashRequest createMobileSignHashRequest() {
        return new MobileSignHashRequest();
    }

    /**
     * Create an instance of {@link MobileSignHashResponse }
     */
    public MobileSignHashResponse createMobileSignHashResponse() {
        return new MobileSignHashResponse();
    }

    /**
     * Create an instance of {@link MobileAuthenticateRequest }
     */
    public MobileAuthenticateRequest createMobileAuthenticateRequest() {
        return new MobileAuthenticateRequest();
    }

    /**
     * Create an instance of {@link EndpointError }
     */
    public EndpointError createEndpointError() {
        return new EndpointError();
    }

    /**
     * Create an instance of {@link MobileAuthenticateResponse }
     */
    public MobileAuthenticateResponse createMobileAuthenticateResponse() {
        return new MobileAuthenticateResponse();
    }

    /**
     * Create an instance of {@link GetMobileAuthenticateStatusRequest }
     */
    public GetMobileAuthenticateStatusRequest createGetMobileAuthenticateStatusRequest() {
        return new GetMobileAuthenticateStatusRequest();
    }

    /**
     * Create an instance of {@link GetMobileSignHashStatusRequest }
     */
    public GetMobileSignHashStatusRequest createGetMobileSignHashStatusRequest() {
        return new GetMobileSignHashStatusRequest();
    }

    /**
     * Create an instance of {@link GetMobileAuthenticateStatusResponse }
     */
    public GetMobileAuthenticateStatusResponse createGetMobileAuthenticateStatusResponse() {
        return new GetMobileAuthenticateStatusResponse();
    }

    /**
     * Create an instance of {@link GetMobileSignHashStatusResponse }
     */
    public GetMobileSignHashStatusResponse createGetMobileSignHashStatusResponse() {
        return new GetMobileSignHashStatusResponse();
    }

}
