//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.26 at 05:42:17 PM EET 
//


package ee.openeid.siga.mobileid.model.mid;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for SessionAwareType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="SessionAwareType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Sesscode" type="{http://www.sk.ee/DigiDocService/DigiDocService_2_3.wsdl}SessionIdType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SessionAwareType", propOrder = {
        "sesscode"
})
@XmlSeeAlso({
        AbstractGetStatusRequestType.class,
        AbstractResponseType.class
})
public abstract class SessionAwareType {

    @XmlElement(name = "Sesscode", required = true)
    protected String sesscode;

    /**
     * Gets the value of the sesscode property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSesscode() {
        return sesscode;
    }

    /**
     * Sets the value of the sesscode property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSesscode(String value) {
        this.sesscode = value;
    }

}
